language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script: python setup.py test
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user:
    secure: "FywKN5Kei5zGI0AdFUdMg7SowBnywxKm5Y8ZuS3Qb4Q/SaMwOTSyQmzyi8fQTA40aSkGdG+k0+aoMO+f/D5ZlOK5s4MeY9yM5v59G1/Vnf1UaPPH8kt7Nex/XFahXvUr1ShklPOwoHgP6cBrD1hnUr5pF9oeMoq+lX05qh2L+nE2+YzNlRqwUmYLYp3ZiLxqhNYyePqYJl9j9kDsxnQtQOreW47AEQS2XcoPHFwHoSz3YsgRaF6bx1+d7oz/eVobtQP0BMAIlBM8cu3KxTk6yt/7wcDR2+ujHwe7hG3SDljSpsLxglUo88ujxSPI0hE6oMXMAiBAenBWY/o40MH0kTOApf5MJVF4OERu5NAikW5RLBtRuH3S3juWQjpqg6B7eAUUoaiPTHpNytuyK7d+DUDBfnN6rPExFVIIWVwTgJQkR5DQdgmvl2JfqK6R0ArsXGo38HPHhl2w4wUokUOFMxDdHWRqj64xumqUK3192r7pD09dZ17gGmz73hS49JlVsK9NUqsRpcGyOAbJdQWLrRCJJhqRaSdmBeQjTx7y5y0GLFKahbv1pTsJL/d46qrVPJvUz8oxt5jJOujw5D9jMg8A1GBg15yKWH1FKlIA5zBFUFwTfDWbuhx73kHLpfZI6iR0IS4YzJJSecY3xCDvwzdiuxqqYenyUzkHDuQ7sGw="
  password:
    secure: "qo1BzuwGqZCnZbTLwCOInju6Ueg07P2trupDoUHlPOo9PCKpEk/X7H77T2kcMkOH+gLahBar86Qw8sfc2Szps/5ARFwZ0dbaX1Ff+w4qxqXqc5kLBfAenKsYWWD2HeR+up1BnpQ5m8mZb82mDYnvu9G77txgaDvDqFlHOynSwfe/G4lxN3gniI63u9eYYXUG/NfFodfmrfF5ti8yXzzYAuBOeVPzYEqiVl9lkfMhImyN50LacmYWYmkOMdgu/+JcYQCAjXftQqSrHdUY4FbcVEVENrTiiHUpfZN8L+YR8LGa7R+NUh4yPFbMoFN4CduOSepAlr3z3ZiL7MV95UhKNZKxE3VwcB76ab6EqWrHZql1dBdR8OlXqfaWm1hxjPgPWCLdOv49s3LJpdSEGNZrldReWdCISDWyw+MKKRSarNG5yp4M3A7KvvHbFFVzkVfWbe474SGLZ17VxrrvSvs9kVhMLAZR553rIUdr1qoRRBqZy/uDVEAgLyIcyHK534V0KWzNYNWtEuMe+NCyJq5S7eUamhQzb1BkyJfSQn4SX+7SAzrNZemXA1QarGt6+OPcI410LaGTufnHbgQXPuNiRNZWHu/K56onPX9q+G+aiAy6/Tmdi8Vt3LZXIOsbsV8oSWMBDIbUCG+Hoy/JYEb3RAch8qe4B+MNqi7wom4Q1YQ="
  on:
    repo: kichik/email-scraper
    tags: true
    python: 3.6
